### ISSUE TITLE
Introduce a dedicated class for handling hexadecimal numbers or use an existing one if available, rather than using strings

### ISSUE THREAD

**Issue by boorich** [ChainSafe/web3.unity#818] opened 2024-01-08 14:01 UTC

**Comment by sneakzttv** [comment] 2024-01-08 14:26
Currently we're using strings as hex is some places and other places we're using nethereum's hex type. We should be changing everything to use nethereum's type so that we achieve uniformity across the board. As well as checking that everything functions as intended.

**Comment by kantagara** [comment] 2024-04-02 08:36
Closing this for now.

**Comment by sneakzttv** [comment] 2024-05-22 22:24
This has been rectified due to recent updates.

**Closed by sneakzttv** 2024-05-22 22:24 UTC
Labels: Priority: P3
