### ISSUE TITLE
[Critical] Unexpected token on 2nd reload error

### ISSUE THREAD

**Issue by RyRy79261** [ChainSafe/web3.unity#416] opened 2023-05-10 15:10 UTC
**Describe the bug**

Intermittently, often with larger games, the 2nd time the game is loaded, it encounters an unexpected token error, but it difficult to assertain what the token is, but the error points to just before an `export` statement 

**To Reproduce**
1. [Go to CryptoSurfers](https://www.cryptosurferz.com)
2. Connect your wallet
3. Refresh 
4. If error occured, error will display in console

**Expected behavior**
Refreshing should not affect the stability of the SDK

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Desktop (please complete the following information):**
 - WebGL game, Chrome & Firefox

**Current suspicions** 

- Scripts no loading at the right time
   - Been tinkering with defers, forced sequential loads, combined loads etc
 - Experimenting with Vite build config as there is a lot of processing in Vite that is different to typical bundlers, @BeroBurny provided a possible solve

**Comment by sneakzttv** [comment] 2023-05-15 11:10
closing this as it's a duplicate of https://github.com/ChainSafe/web3.unity/issues/374

**Closed by sneakzttv** 2023-05-15 11:10 UTC
Labels: Type: Bug
