### ISSUE TITLE
Please continue the development of mobile branch

### ISSUE THREAD

**Issue by moheydy** [ChainSafe/web3.unity#60] opened 2021-12-22 22:43 UTC
I think everyone is aware of the this issue(bug deep link), But in the end they probably fix this issue

**Comment by KBryan** [comment] 2021-12-23 17:44
As soon as the issue is fixed we will continue to work on the mobile implementation. As discussed this is on MetaMask so closing this issue as it is not primarily on our side.

**Closed by KBryan** 2021-12-23 17:44 UTC
Labels: Type: Feature
