### ISSUE TITLE
R&D - Ramp FIAT on off integration - Desktop

### ISSUE THREAD

**Issue by kantagara** [ChainSafe/web3.unity#638] opened 2023-09-28 13:11 UTC
This one is only marked as R&D since we're not sure it's possible to do it.

**Comment by boorich** [comment] 2023-12-06 13:24
Depends on successful market reception.

**Comment by sneakzttv** [comment] 2024-06-10 09:31
Closed as the issue is redundant now.

**Closed by sneakzttv** 2024-06-10 09:31 UTC
Labels: Status: Blocked, Type: Feature, Version: Integrations
