### ISSUE TITLE
TypeError e.map when calling Web3GL.SendContract

### ISSUE THREAD

**Issue by CryptoGnome** [ChainSafe/web3.unity#256] opened 2022-11-02 21:47 UTC
**Describe the bug**
Calling a the function below using a webGL build that asks for an array of uints
```
    function openPacks(uint256[] memory num) public {
        require( !_paused,  "Minting Packs Paused" );
        require(num.length < 100, "You can open a maximum of 100 Packs Per TX" );
        require((totalSupply() + 1) <= maxSupply, "max supply");
        uint nonce = roll();
        //loop through array and mint packs, each pack has 5 cards
        for (uint256 i = 0; i < num.length; i++) {
            require(packs.ownerOf(num[i]) == msg.sender, "Sender does not own this pack");
            //burn pack to dead address
            packs.transferFrom(msg.sender, 0x000000000000000000000000000000000000dEaD, num[i]);
            for (uint256 j = 0; j < 5; j++) {
                string memory cardURI = Strings.toString(pullCard(nonce));
                _safeMint(msg.sender, totalSupply());
                //set tokenURI
                _setTokenURI(totalSupply(), cardURI); 
            }
        }          
    }
```

**To Reproduce**
```
 async public void open_packs(){
        string method = "openPacks";
        //calculate gasLimit based on amount of packs to open
        int gasLimitCalc = (1 * 900000);
        string gasLimit = gasLimitCalc.ToString();
        string gasPrice = "";
        string value = "0";

        object[] obj = {14};
        string args = JsonConvert.SerializeObject(obj);
        Debug.Log("Args: " + args);

        try {
            string response = await Web3GL.SendContract(method, cardABI, cardContract, args, value, gasLimit, gasPrice);
            Debug.Log("response: " + response);

        } catch (Exception e) {
            Debug.Log("Error: " + e);
        }
    }
 ```
**Expected behavior**
I have other functions working and have used chainsafe for other projects and have not seen this issue I tried sending the function multiple different ways but they all fail the same

### Full contracts are on polygon test net:

Packs:
https://mumbai.polygonscan.com/address/0x1e4b2c9006e399bc23de1f8476452c254fa20dfd#code
Cards:
https://mumbai.polygonscan.com/address/0x03bcaa53f45dc69764d636dae0b2e121cf2eac8d#code

The process is mint the pack/packs, setApproval for all on the packs so the Cards Contract can move the packs,
then call the openPacks function on the cards which should allow you to burn the back to open a pack. This works in hardhat, js, anmd etherscan. Having this issue only here.

**Screenshots**
![image](https://user-images.githubusercontent.com/33667144/199608505-f27df35b-e911-4576-bd91-47a7400dff2d.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 107.0.5304.87

**Comment by sneakzttv** [comment] 2022-11-02 23:00
not a bug, it's a string formatting error, closing this. "[" + 14 + "]";

**Closed by sneakzttv** 2022-11-02 23:00 UTC
Labels: Type: Bug
