### ISSUE TITLE
The ChainSafe/web3.unity package not working on Android 12.0. The package not give the access with the address of meta mask 

### ISSUE THREAD

**Issue by TauseefAhmaad** [ChainSafe/web3.unity#109] opened 2022-03-08 05:37 UTC
i am using ChainSafe/web3.unity latest package in the unity and make the android build . when i run the build on android OS device (Samsung A52) , its open the metamask but not copy the wallet address and other request the address as you upload the videos on youtube . i follow the all things and but login in unity with this. 
i am attach the video please review the video

https://user-images.githubusercontent.com/99240552/157173191-c09b7b59-cb0f-4d0f-b229-58dea6216f7d.mp4

**Comment by KBryan** [comment] 2022-03-08 12:52
You need to open the browser i.e. Chrome use the copy link to the clipboard then return back to the application.

**Comment by mcdeimon** [comment] 2022-03-08 18:28
Hello! Any update on this?

**Comment by CocoJr** [comment] 2022-03-15 07:57
Metamask got an upgrade but the problem is still here.

**Comment by brian-kryptomon** [comment] 2022-03-19 22:43
I am also experiencing the same issue even after the supposed fix from Metamask 4.2.2 - only happens on Android 12 not 11.

**Comment by brian-kryptomon** [comment] 2022-03-19 22:44
> Metamask got an upgrade but the problem is still here.

do you have a bug opened after they supposedly fixed it? I just logged one:

https://github.com/MetaMask/metamask-mobile/issues/3923

If you want to add your video to it that would be awesome.

**Comment by brian-kryptomon** [comment] 2022-03-20 14:55
@KBryan is this still for sure a metamask issue? I logged another issue there as the one you referenced is marked as closed in 4.2.2

**Comment by KBryan** [comment] 2022-03-20 14:59
I will need to test this out tomorrow. It's been brought to my attention that this has been resolved on their end. Although, having users report the same issue.

**Comment by KBryan** [comment] 2022-03-21 21:56
Looks like the same thing is happening on Android 12 with this recent update. Doing some more tests and will confirm tomorrow.

**Comment by brian-kryptomon** [comment] 2022-03-22 11:33
@KBryan thanks for following up - i've been trying to get the attention of someone on the metamask side but no luck so far.

**Comment by leon-do** [comment] 2022-03-25 13:12
Did tests on the latest MetaMask build. It has not been fixed. @KBryan @brian-kryptomon will have to open up a new issue and specify for android 12

**Comment by brian-kryptomon** [comment] 2022-03-25 23:47
I had an issue opened and Curtis on the Metamask side responded and said it
was supposedly fixed in 4.3.1 but I just downloaded that and the same issue
occurred. DId you test on 4.3.1?

**Comment by brian-kryptomon** [comment] 2022-03-26 14:08
We did more testing and when I downloaded the update from the play store for 4.3.1 it didn’t work but then I uninstalled and installed via the APK on github it now works. 

I asked the MetaMask team to investigate. 

Thanks. 

Brian M. Bento

**Comment by KBryan** [comment] 2022-03-28 14:20
I'm also seeing this also. Uninstalling and reinstalling the APK from GitHub now works as expected. I'll add my findings as well. Thanks, @brian-kryptomon

**Comment by KBryan** [comment] 2022-05-04 16:03
Also, noted. Closing this issue.

**Closed by KBryan** 2022-05-04 16:03 UTC
Labels: Type: Bug
