### ISSUE TITLE
Lootboxes not working with Sepolia

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#779] opened 2023-11-30 14:37 UTC
**Describe the bug**
Now the error with the login + lootboxes is fixed, we should be able to execute the Lootboxes sample with another network that is not the hardhat setup.
But looks like the **ChainlinkLootboxSampleLauncher** it was made by only work with hardhat.

**Steps**
1. Use the scene [SampleLogin or SampleLogin - Web3Auth]
2. Put "SampleLootboxes" in **Scene To Load** script
3. Add SampleLootboxes scene to the Build settings
4. Click play in Unity
5. Login with [Web3Auth or Remote wallet]
6. See error

**Expected behavior**
Lootboxes screen loads correctly like in hardhat

**Console errors**
```
WalletException: No account with index #2 available
ChainSafe.Gaming.Wallets.JsonRpcWallet.QueryAddress () (at <3d61c3313e7541b0a6fd2f9d8fd998f8>:0)
ChainSafe.Gaming.Wallets.JsonRpcWallet.WillStartAsync () (at <3d61c3313e7541b0a6fd2f9d8fd998f8>:0)
ChainSafe.Gaming.Web3.Web3.InitializeAsync () (at <aa77ff17ceec43bfb7738b2f5872cf37>:0)
ChainSafe.Gaming.Web3.Build.Web3Builder.LaunchAsync () (at <aa77ff17ceec43bfb7738b2f5872cf37>:0)
LootBoxes.Chainlink.ChainlinkLootboxSampleLauncher.Awake () (at Assets/Samples/web3.unity SDK Lootboxes/1.0.0/Chainlink Lootbox Sample/Scripts/ChainlinkLootboxSampleLauncher.cs:39)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <b6c5d0f08ddf477186f780f49bb14dee>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
```

**Reproducible Code Snippet (if applicable):**
If the issue is related to a specific piece of code, provide the relevant code snippet here.
```
private async void Awake()
        {
            web3 = await new Web3Builder(new Web3Config())
                .Configure(services =>
                {
                    services.UseUnityEnvironment();
                    services.UseRpcProvider();
                    services.Debug().UseJsonRpcWallet(new JsonRpcWalletConfig { AccountIndex = 2 });
                    services.UseChainlinkLootboxService(new LootboxServiceConfig
                    {
                        ContractAddress = "0x1993e2dD323B5dcBd8b52dB7d370bC36D280424B",
                        ContractAbi = ContractAbi
                    });
                    services.AddSingleton<Erc1155MetaDataReader>();
                })
                .LaunchAsync();

            lootBoxScene.Configure(
                web3.Chainlink().Lootboxes(),
                web3.ContractBuilder,
                web3.ServiceProvider.GetRequiredService<Erc1155MetaDataReader>());

            lootBoxScene.Launch();
        }
```

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [main]
 - Unity Version: [e.g., 2022.1]
 - Operating System: [Mac]

**Comment by sneakzttv** [comment] 2024-01-08 14:14
Alternate chain contracts for lootboxes

0xF899Bc1f149030c3912f1Cb473A7b2db0ed9cE5f - Sepolia Testnet LootboxFactory
0xfa97aCce8E4929e6d13a7c418BfbA0311e9D3Bfd - Mumbai Testnet LootboxFactory
0xfa97aCce8E4929e6d13a7c418BfbA0311e9D3Bfd - Binance Testnet LootboxFactory
0xfa97aCce8E4929e6d13a7c418BfbA0311e9D3Bfd - Fuji Testnet LootboxFactory
0xfa97aCce8E4929e6d13a7c418BfbA0311e9D3Bfd - Fantom Testnet LootboxFactory

**Comment by lastperson** [comment] 2024-01-22 14:44
```
services.Debug().UseJsonRpcWallet(new JsonRpcWalletConfig { AccountIndex = 2 });
```
Why the account index is hardcoded to 2? Seems like the problem is not related to lootboxes itself, but the fact that the connected wallet does not have specified account.

**Comment by sneakzttv** [comment] 2024-01-25 14:30
actually a decent find, this was for testing purposes. @oleksandrchainsafe does this solve the issue?

**Comment by kantagara** [comment] 2024-02-20 15:55
@juans-chainsafe closing this issue for good. 
Because the lootbox sample itself is a very VERY hacky thing where we're essentially creating a local environment that has all of those lootboxes, and we're stitching those lootboxes in a local environment where we're creating a locally created wallet (for that same environment). That is why we can't make a universal solution because 'out in the wild' their amount is always finite (i.e. even if we put our own lootboxes out), we'd always have to refill their amount, and don't know if that costs money, but it's a burden that I don't want anyone to carry in the team :D 
So for now I'm closing this one.

**Closed by kantagara** 2024-02-20 15:55 UTC
Labels: Type: Bug
