### ISSUE TITLE
Editor login broken

### ISSUE THREAD

**Issue by achia** [ChainSafe/web3.unity#754] opened 2023-11-22 01:25 UTC
**Describe the bug**
When running the sample login scene in v2.5.3 and hitting use existing wallet. Also occurs when in unity editor running the login the old 2.5.0 way but using the new BuildAsync() replacement.

**Steps**
1. Use the scene [SampleLogin or SampleLogin - Web3Auth]
2. Login with [Web3Auth or Remote wallet]
3. Error

**Expected behavior**
A web page should open and connect to my metmask for login.

**Console errors**
NullReferenceException: Object reference not set to an instance of an object
ChainSafe.Gaming.MultiCall.MultiCall..ctor (ChainSafe.Gaming.Evm.Contracts.IContractBuilder builder, ChainSafe.Gaming.Web3.IChainConfig chainConfig, ChainSafe.Gaming.MultiCall.MultiCallConfig config) (at <acddae23e24d42e7b2fc1d191340827c>:0)
System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) (at <f646c7a159d243a7909d5204af0f0c56>:0)
--- End of stack trace from previous location where exception was thrown ---
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context) (at <79a2e2ad4e414715b9c4f3c252f5a8c3>:0)

**Screenshots/Video**
If applicable, add screenshots or screen recordings that help visualize the issue.

**Reproducible Code Snippet (if applicable):**
 public async void Connect()
    {
            useWebPageWallet = Application.platform != RuntimePlatform.WebGLPlayer;
            builder = new Web3Builder(ProjectConfigUtilities.Load())
            .Configure(ConfigureCommonServices)
            .Configure(services =>
            {
                if (useWebPageWallet)
                {
                    services.UseWebPageWallet();
                }
                else
                {
                    services.UseWebGLWallet();
                }
            });
            await ProcessConnection();
    }
        private async Task ProcessConnection()
    {
        Debug.Log("Connecting");
        try
        {
            web3 = await builder.BuildAsync();
            Web3Accessor.Set(web3);
            PlayerPrefs.SetString("PlayerAccount", await Web3Accessor.Web3.Signer.GetAddress());
            Debug.Log("Connected!");
            SceneManager.LoadScene(SceneManager.GetActiveScene().buildIndex + 1);
        }
        catch (Web3Exception e)
        {
            Debug.Log(e + "Connection failed. Try again.");
            throw;
        }
    }

**Desktop (please complete the following information):**
 - Chainsafe SDK version: 2.53
 - Unity Version: 2022.3.11f
 - Operating System: MacOS 14

**Additional context**
Need to be able to proxy whats happening in WebGL to develop in unity editory without making a web build each time.

**Comment by sneakzttv** [comment] 2023-11-28 11:51
Closing this as it has been tested and is functioning as intended in the latest version.

**Closed by sneakzttv** 2023-11-28 11:51 UTC
Labels: Type: Bug
